version: "3.8"

services:

    # PHP
    php:
        build: .docker/php
        container_name: mitsuBp_php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
        depends_on:
            - db
        networks:
            - my_network

    # Nginx
    nginx:
        image: nginx
        container_name: mitsuBp_nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
            - npm
        networks:
            - my_network

    # DATABASE (MySQL)
    db:
      image: mysql:8.0.19
      container_name: mysql_mitsuBP
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: BPCOLORDB 
        MYSQL_USER: HanThamarat
        MYSQL_PASSWORD: root
      ports:
        - "3307:3306"
      volumes:
        - "./.docker/db:/var/lib/mysql:rw"
      networks:
        - my_network

    npm:
      image: node:current-alpine
      container_name: mitsuBp_npm
      volumes:
        - .:/var/www
      entrypoint: ["npm", "run", "dev"]
      working_dir: /var/www
      networks:
        - my_network
  
networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
